export const countries = [
  { code: "", label: "Any Country" },
  { code: "ua", label: "Ukraine" },
  { code: "us", label: "USA" },
  { code: "de", label: "Germany" },
  { code: "fr", label: "France" },
  { code: "es", label: "Spain" },
  { code: "it", label: "Italy" },
  { code: "pl", label: "Poland" },
  { code: "nl", label: "Netherlands" },
  { code: "se", label: "Sweden" },
  { code: "no", label: "Norway" },
  { code: "dk", label: "Denmark" },
  { code: "fi", label: "Finland" },
  { code: "pt", label: "Portugal" },
  { code: "gr", label: "Greece" },
  { code: "tr", label: "Turkey" },
  { code: "jp", label: "Japan" },
  { code: "cn", label: "China" },
  { code: "kr", label: "South Korea" },
  { code: "br", label: "Brazil" },
  { code: "ar", label: "Argentina" },
  { code: "mx", label: "Mexico" },
  { code: "ru", label: "Russia" },
  { code: "by", label: "Belarus" },
  { code: "kz", label: "Kazakhstan" },
  { code: "in", label: "India" },
  { code: "au", label: "Australia" },
  { code: "ca", label: "Canada" },
  { code: "za", label: "South Africa" },
  { code: "il", label: "Israel" },
  { code: "ae", label: "UAE" },
  { code: "eg", label: "Egypt" }
];
